# Generated by Django 2.2.2 on 2019-08-25 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ad')),
                ('content', models.TextField(verbose_name='Açıklama')),
                ('address', models.TextField(verbose_name='Adres')),
                ('phone', models.CharField(max_length=11, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('slug', models.CharField(max_length=255, verbose_name='Slug')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yetkili')),
                ('staff', models.ManyToManyField(blank=True, related_name='dealers', related_query_name='dealer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bayi',
                'verbose_name_plural': 'Bayiler',
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ad')),
                ('content', models.TextField(verbose_name='Açıklama')),
                ('address', models.TextField(verbose_name='Adres')),
                ('phone', models.CharField(max_length=11, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('slug', models.CharField(max_length=255, verbose_name='Slug')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yetkili')),
                ('dealers', models.ManyToManyField(blank=True, related_name='distributors', related_query_name='distributor', to='project.Dealer')),
                ('staff', models.ManyToManyField(blank=True, related_name='distributors', related_query_name='distributor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Distribütör',
                'verbose_name_plural': 'Distrübütörler',
            },
        ),
    ]
