# Generated by Django 2.2.2 on 2019-06-30 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_book_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyBook',
            fields=[
            ],
            options={
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('learning.book',),
        ),
    ]
