# Generated by Django 2.2.2 on 2019-06-30 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_proxybook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcompany',
            name='author',
        ),
        migrations.RemoveField(
            model_name='gamecompany',
            name='author',
        ),
        migrations.RemoveField(
            model_name='intro',
            name='book_ptr',
        ),
        migrations.DeleteModel(
            name='ProxyBook',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookCompany',
        ),
        migrations.DeleteModel(
            name='GameCompany',
        ),
        migrations.DeleteModel(
            name='Intro',
        ),
    ]
