# Generated by Django 2.2.2 on 2019-08-25 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
